---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-pd
  labels:
    app: nginx
    purpose: servicedemo
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginxp
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
        
          

          
